apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  annotations: {}
  labels:
    scenario: '1'
  name: scenario1
spec:
  selector:
    matchLabels:
      scenario: '1'
  template:
    metadata:
      labels:
        fleet: scenario1
    spec:
      applications: []
      config: []
      os:
        image: edge-registry.itix.fr/demo-edge-retail/scenario1:latest
      config:
      - name: scenario1-config
        configType: GitConfigProviderSpec
        gitRef:
          path: /flightctl/scenario1
          repository: demo-edge-retail
          targetRevision: main
  systemd:
    matchPatterns:
      - nextcloud-*.service
      - nextcloud-*.target
---
apiVersion: flightctl.io/v1alpha1
kind: Fleet
metadata:
  annotations: {}
  labels:
    scenario: '4'
  name: scenario4
spec:
  selector:
    matchLabels:
      scenario: '4'
  template:
    metadata:
      labels:
        fleet: scenario4
    spec:
      applications: []
      config: []
      os:
        image: edge-registry.itix.fr/demo-edge-retail/scenario4:latest
      config:
      - name: scenario4-config
        configType: GitConfigProviderSpec
        gitRef:
          path: /flightctl/scenario4/sites/{{ getOrDefault .metadata.labels "site" "default" }}/
          repository: demo-edge-retail
          targetRevision: main
  systemd:
    matchPatterns:
      - odoo-*.service
      - odoo-*.target
